name: Enable Copilot Coding Agent
on:
  push:
    branches:
      - main
permissions:
  contents: write
  pull-requests: write
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Copilot Coding Agent
        run: echo "Copilot Coding Agent aktiviert."
